// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace UDP_raspberry_pi_modtager
{
    public partial class Promille
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Promille1 { get; set; }
        public DateTime Time { get; set; }
    }
}